### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by jcubic** [mattrobenolt/jwt-node#10]
Do you consider publishing the actual source code of the package? There is the license in README but this is not Open Source because the code is minifed. The requirement for something to be Open Source is to provide readable code.

**Comment by mattrobenolt** [comment]
What do you mean? It's been open source, it's in this repo, for a long time.

I wouldn't really recommend using this tho. It's severely unmaintained, was probably never good, and I'm positive there are better alternatives.

**Comment by mattrobenolt** [comment]
Oh, you edited the comment. The original code I adapted this from was minified as well iirc. I didn't author most of this.

**Comment by mattrobenolt** [comment]
So I guess, short answer is no. I didn't author the original minified code to begin with. But I'll reiterate, I wouldn't recommend using this. It's archived for a reason.

**Comment by jcubic** [comment]
I would not call this source:

```javascript
"use strict";var sjcl={cipher:{},hash:{},mode:{},misc:{},codec:{},exception:{corrupt:function(a){this.toString=function(){return"CORRUPT: "+this.message};this.message=a},invalid:function(a){this.toString=function(){return"INVALID: "+this.message};this.message=a},bug:function(a){this.toString=function(){return"BUG: "+this.message};this.message=a}}};
sjcl.cipher.aes=function(a){this.h[0][0][0]||this.w();var b,c,d,e,f=this.h[0][4],g=this.h[1];b=a.length;var h=1;if(b!==4&&b!==6&&b!==8)throw new sjcl.exception.invalid("invalid aes key size");this.a=[d=a.slice(0),e=[]];for(a=b;a<4*b+28;a++){c=d[a-1];if(a%b===0||b===8&&a%b===4){c=f[c>>>24]<<24^f[c>>16&255]<<16^f[c>>8&255]<<8^f[c&255];if(a%b===0){c=c<<8^c>>>24^h<<24;h=h<<1^(h>>7)*283}}d[a]=d[a-b]^c}for(b=0;a;b++,a--){c=d[b&3?a:a-4];e[b]=a<=4||b<4?c:g[0][f[c>>>24]]^g[1][f[c>>16&255]]^g[2][f[c>>8&255]]^
g[3][f[c&255]]}};
```

So even if you have a license no one can modify it, and this is a requirement for something to be called Open Source.

Also, the repository is not archived. I never did this myself but if this is not maintained and archived then maybe it will be a good idea to Archive it using the GitHub interface to show a big warning sign.

**Comment by mattrobenolt** [comment]
Fair. I thought it was archived. Sorry that this repository that hasn't been updated in literally 12 years isn't up to your standards. My apologies. I will archive when I'm at a computer ASAP just for you.
