### ISSUE TITLE
Cannot install node-base64 on Windows

### ISSUE THREAD

**Issue by danielkcz** [mattrobenolt/jwt-node#2]
I don't know when this became dependency, but it doesn't seems good to rely on module in version 0.0.1...

After bit searching I had found originating repo ... https://github.com/astro/node-base64

He has even disabled issue reporting. Can you please consider to use some other module for B64? This is some rather problematic...

```
$ npm install -S node-base64
\
> node-base64@0.0.1 install C:\workspace\alpha\node_modules\node-base64
> ./install.sh

'.' is not recognized as an internal or external command, operable program or batch file.

npm ERR! node-base64@0.0.1 install: `./install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-base64@0.0.1 install script.
npm ERR! This is most likely a problem with the node-base64 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./install.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-base64
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodej
s\\node_modules\\npm\\bin\\npm-cli.js" "install" "-S" "node-base64"
npm ERR! cwd C:\workspace\alpha
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by danielkcz** [comment]
Bah...you are not even using that library in actual code...

**Comment by mattrobenolt** [comment]
I am using the library. And I can reproduce on other systems that aren't Windows as well.

So I'm open to using a different library. The code just doesn't look compatible with modern node versions. I'm sure it can be traced back to which version it started failing.

**Comment by danielkcz** [comment]
That's really odd, because module is called `node-base64` this it is stored in `node_modules/node-base64`, but you are requiring `base64`. I kinda doubt it can work like this...

Either way nevermind me. I kinda realized that I wasn't using your library before anyway. I just saw variable `jwt` in some of my code, but later I found out that I am actually using module `jsonwebtoken` :) I suppose you don't need to worry about this one unless somebody is actively using it.

**Comment by mattrobenolt** [comment]
There's native base64 encoding in modern node, so I'll take a look and see if I can just swap that in instead.

fwiw, it does work when you just `require('base64')` The `node-` part is ignored.

Leaving the ticket open until I fix it.

**Comment by danielkcz** [comment]
Uhh, I don't know where did you got such information, but it's definitely false. Imagine what would node possibly do if you would have both `base64` and `node-base64` in your `node_modules` directory. I have just [tested it](https://dl.dropboxusercontent.com/u/1791518/rq.zip) and believe me that it doesn't ignore anything. Take or forget, I am not gonna argue about such obvious case ;)

**Comment by mattrobenolt** [comment]
I dunno, it worked at some point. :) I did use this once. I'm also not a node developer, so I have no real idea and don't care to investigate.

**Comment by olizilla** [comment]
Would you consider adding a "not maintained" notice on the readme? I was tracking down the same issue with base64 failing to install, and it took me an hour to realise that I'd actually meant to install [node-jsonwebtoken](https://github.com/auth0/node-jsonwebtoken)!
