### ISSUE TITLE
difference? And an addition to your code

### ISSUE THREAD

**Issue by mhombach** [mattrobenolt/jwt-node#4]
Hey,
First, can you tell me what is the difference between you package and the official one? Because i can't see any.
Also, in your readme, you wrote this line:
`expires: Math.round((new Date().getTime()/1000)) + 3600`
Just for clarification, this is no safe way to create the expire-attribute because with `Date.getTime()` you will run into timezone-errors very quick.
Would be glad to get an anwer on my question^^

**Comment by mattrobenolt** [comment]
I don’t know. This code is super old, and I would not use. I’m sure there are better versions now.

**Comment by mhombach** [comment]
@mattrobenolt uhm, maybe you want to referennce the official JWT package on your front side then? It's a little bit irritating if someone thinks that this package is the way to go when using JWT in nodeJS ^^°

**Comment by mattrobenolt** [comment]
Mind linking me to the official one? To be fair, this repository hasn't been updated since 2012 and has 22 stars. I don't think there has really been confusion until now, but I'm happy to mention this if I'm linked to the correct one to use?

**Comment by mhombach** [comment]
Sure :)
https://jwt.io

The exakt package is `jsonwebtoken` :)
Thanks, really appreciate it!
Since that is the correct package, every update on the JWT schema and library will be updated in that one :)

**Comment by JBallin** [comment]
I agree that this is confusing, I ran `npm install jwt` today instead of `npm install jsonwebtoken`.

Is there a way to have `npm install jwt` log a message saying something like: 

> "jwt" is no longer being maintained. Did you mean "jsonwebtoken"?

I'm happy to try and submit a PR if needed. Thanks!

**Comment by mattrobenolt** [comment]
I'd be open to a PR to change that since i don't know how. Or some other suggestion here. Can I relinquish the package name and let whoever is the owner of `jsonwebtoken` to take over?

**Comment by mhombach** [comment]
@mattrobenolt hey :) i just tried to find some soultion and since unpublishing a package is consideres "bad practice", you could mark the package as "deprecated" (just google how to do it) or you could add these lines in your package.json file:

`"scripts": {
    "preinstall": "\r\n#######################################\r\n\r\nTHIS PACKAGE IS DEPRECATED FOR YEARS AND IS NO LONGER SUPPORTED.\r\nPLEASE USE THE OFFICIAL 'jsonwebtoken' PACKAGE INSTEAD !!!\r\n\r\n####################################### && exit 1"
  },`

It could be that the package gets installed though, but the message should be clear. In my opinion marking this package as deprecated isnt enough since there are years of developing between this and the official package, so imho nobody should consider to use it and instead jump to the official package :)

After that, you could get in contact with the jwt team and ask, how they would like to proceed with this repo in the future. maybe they can create some alias for the package.
