### ISSUE TITLE
Cannot install JWT!

### ISSUE THREAD

**Issue by contourintegrals** [mattrobenolt/jwt-node#5]
Hello!
When I do **npm install jwt**
It throws an error:
>node-base64@0.0.1 install C:\Users\Lenovo\AppData\Roaming\npm\node_modules\jwt\node_modules\node-base64
>./install.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-base64@0.0.1 install: `./install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-base64@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2019-10-17T04_08_12_681Z-debug.log
Please suggest me!

**Comment by mattrobenolt** [comment]
For one, this is a really really old and unmaintained library. And for two, the failure is from a dependency this uses, `node-base64` which apparently isn't compatible with Windows. So unfortunately, there's not much I can do here.
