### ISSUE TITLE
`npm install` fails on the  jwt-node repo on PowerPC

### ISSUE THREAD

**Issue by sarveshtamba** [mattrobenolt/jwt-node#6]
Facing the following error while running npm install on the jwt-node repo on PowerPC-ppc64le:

```
> node-base64@0.0.1 install /home/tester/jwt/node_modules/node-base64
> ./install.sh
./install.sh: line 3: node-waf: command not found
```
**Node.js version: 12.16.1

**Comment by xprnio** [comment]
1. Last commit to this repo was 8 years ago
2. You're probably looking for a [different repo](https://github.com/auth0/node-jsonwebtoken)

**Comment by sarveshtamba** [comment]
@xprnio I understand this repo is quite old and last commit was 8 years old, however I'm trying to build this repo itself. Any help would be appreciated. TIA.

**Comment by xprnio** [comment]
@sarveshtamba In that case, [here's part of the solution](https://stackoverflow.com/questions/16317976/node-waf-not-found). Basically, `node-waf` was replaced by `node-gyp`. Why is it trying to use `node-waf` you might ask then. Well, that's part of [node-base64's install script](https://github.com/brainfucker/node-base64/blob/master/install.sh). So in order to get `node-jwt` to work, you'd also need to fork `node-base64` and change the install script to use `node-gyp` instead of `node-waf`. Seems like a lot of effort for something like this, but hey, whatever floats your goat.

**Comment by sarveshtamba** [comment]
Thanks @xprnio 
Made the following changes to `node-base64` repo and tried to build it using `make` command:-
```
bash-4.2# git diff
diff --git a/install.sh b/install.sh
index 4b035a5..701698e 100644
--- a/install.sh
+++ b/install.sh
@@ -1,2 +1,2 @@
 #!/bin/bash
-node-waf configure build
+node-gyp configure build
diff --git a/makefile b/makefile
index 0f9f70e..0c0a1f9 100644
--- a/makefile
+++ b/makefile
@@ -1,5 +1,5 @@
 all:
-       node-waf configure build && mkdir -p ~/.node_libraries && cp ./build/default/base64.node ~/.node_libraries/base64.node
+       node-gyp configure build && mkdir -p ~/.node_libraries && cp ./build/default/base64.node ~/.node_libraries/base64.node
 tests:
        node ./test.js
 clean:
```
I am seeing the following errors which I am currently trying to fix.
```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make[1]: Entering directory `/home/tester/node-base64/build'
  CXX(target) Release/obj.target/binding/base64.o

../base64.cc:170:1: error: 'Handle' does not name a type
 Handle<Value>
 ^
../base64.cc:192:1: error: 'Handle' does not name a type
 Handle<Value>
 ^
../base64.cc:215:23: error: variable or field 'init' declared void
 extern "C" void init (Handle<Object> target)
                       ^
../base64.cc:215:23: error: 'Handle' was not declared in this scope
../base64.cc:215:36: error: expected primary-expression before '>' token
 extern "C" void init (Handle<Object> target)
                                    ^
../base64.cc:215:38: error: 'target' was not declared in this scope
 extern "C" void init (Handle<Object> target)
                                      ^
make[1]: *** [Release/obj.target/binding/base64.o] Error 1
make[1]: Leaving directory `/home/tester/node-base64/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v12.16.1/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.14.0-115.14.1.el7a.ppc64le
gyp ERR! command "/root/.nvm/versions/node/v12.16.1/bin/node" "/root/.nvm/versions/node/v12.16.1/bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/tester/node-base64
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
make: *** [all] Error 1
```
Let me know if anything looks familiar or if I am missing anything.

**Comment by sarveshtamba** [comment]
Hi @xprnio @mattrobenolt ,
I tried an alternate node-base64 `https://github.com/chentsulin/node-base64.git` repository as below and looks like it works with jwt-node. Let me know if this is correct approach.
```
bash-4.2# git clone https://github.com/chentsulin/node-base64.git
Cloning into 'node-base64'...
remote: Enumerating objects: 35, done.
remote: Total 35 (delta 0), reused 0 (delta 0), pack-reused 35
Unpacking objects: 100% (35/35), done.

bash-4.2# git clone https://github.com/mattrobenolt/jwt-node.git
Cloning into 'jwt-node'...
remote: Enumerating objects: 26, done.
remote: Total 26 (delta 0), reused 0 (delta 0), pack-reused 26
Unpacking objects: 100% (26/26), done.

bash-4.2# cd jwt-node/

bash-4.2# npm install ../node-base64/
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN jwt@0.2.0 No license field.

+ node-base64@0.0.1
added 1 package and audited 1 package in 0.531s
found 0 vulnerabilities

bash-4.2# npm install
npm WARN jwt@0.2.0 No license field.

audited 1 package in 0.327s
found 0 vulnerabilities

bash-4.2# npm list -g | grep -i jwt

bash-4.2# npm list |  grep -i jwt
jwt@0.2.0 /home/tester/jwt-node

bash-4.2# npm install -g
+ jwt@0.2.0
added 1 package from 1 contributor in 0.108s

bash-4.2# npm list -g | grep -i jwt
+-- jwt@0.2.0 -> /home/tester/jwt-node
```

**Comment by xprnio** [comment]
These problems seem to be way out of my area of experice, but I do have a few suggestions.
- Unless you *really* need to use this, just use `jsonwebtoken`. This repo has not been maintained, nor have most of it's dependencies. Trust me, unless you have a proper reason for why you specifically need to get this repo to work, just don't even try.
- Alternatively, if you do think that you really need to get this repo to build properly, use a version of Node that still has `node-waf`. This is your best (and probably only) bet on getting this to work. According to some sources, `node-waf` was deprecated in `v0.8` and removed in `v0.10`, so you should probably try a version of Node within that range.

**Comment by xprnio** [comment]
Update

After attempting to install the dependencies using `v0.9.12`, I keep getting a certificate trust error, so my guess is that using a severely outdated version of Node doesn't really help either. So sadly it seems that you are SOL.

**Comment by mattrobenolt** [comment]
I dunno what’s happening here, but yeah, don’t use this.
